### ISSUE TITLE
Super early development TODO

### ISSUE THREAD

**Issue by HackerDaGreat57** [HackerDaGreat57/np#1]
- [ ] Finish planning what `project.json` is supposed to look like (write JSON by hand, basically)
- [ ] Figure out `jq` JSON parsing (and writing)
- [ ] Finish the "new project" wizard (`jq` will be needed to write the generated JSON file with variables entered by the user in the wizard)

**Comment by HackerDaGreat57** [comment]
the json file looks pretty good as of commit [9effb11](https://github.com/HackerDaGreat57/np/commit/9effb11ecbae3a912c37a62a4fc533cef4a0eb5d), will modify later if needed.

**Comment by HackerDaGreat57** [comment]
looks like jq parsing isn't a priority (and I severely misunderstood its purpose); working on new project wizard

**Comment by HackerDaGreat57** [comment]
We don't need a wizard... I should have realized this before I finished half of it 😅

**Comment by HackerDaGreat57** [comment]
Figured out how to get F&R to work with `jq`. Project name successfully gets replaced with default. Working on other values now.

**Comment by HackerDaGreat57** [comment]
Done with all basic replacements. Now to figure out configuration insertion....

**Comment by HackerDaGreat57** [comment]
Configuration insertion works and is stable. Working on help menu...

**Comment by HackerDaGreat57** [comment]
The help menu looks complete for now. See #2 if you'd like to help make it look better on smaller terminals (with better wrapping).

VSCode Remote Server just stopped working for some stupid reason... how wonderful 🙄 I won't code until it starts working again since I'm not pulling out my bulky 15" laptop on the sofa.

**Comment by HackerDaGreat57** [comment]
Code server is back up. Getting back to work on `-n | --no-defaults`.

**Comment by HackerDaGreat57** [comment]
Halfway done with documentation. Looks good so far! (partial screenshot to highlight coloring)
![image](https://github.com/HackerDaGreat57/np/assets/70416002/c68db475-c9e9-4f16-84fd-9b517e95ef36)

**Comment by HackerDaGreat57** [comment]
done with `-d | --documentation`!

Now prototyping a simple build script that _should_ be generated by the program.

**Comment by HackerDaGreat57** [comment]
Since some lines of text printed by the script can be pretty damn long so I figured out how to get some rudimentary text wrapping working with GNU coreutils' `fmt`. It's not perfect though, the indentation preservation is not exactly perfect. Updated #2 accordingly.

**Comment by HackerDaGreat57** [comment]
Not really in the "super early" stage anymore, changed title

**Comment by HackerDaGreat57** [comment]
I've not done a lot of research and experimentation on how exactly I'm supposed to build dynamic/static libraries with GCC. But the information I've skimmed suggests that we need to run special commands after compilation to do it. So, I introduced an `aftercompilationoverride` option that lets the user run any custom commands after compilation is done.

**Comment by HackerDaGreat57** [comment]
Done adding bundles and megabundles to JSON.

Will start working on the build script Very Soon Now™.

**Comment by HackerDaGreat57** [comment]
So instead of working on the build script like I was supposed to I made argument parsing much better and mostly position-independent in the main `np` script. But hey, progress is progress 🤷🏽‍♂️

**Comment by HackerDaGreat57** [comment]
I also added functionality for using compilers other than GCC.

**Comment by HackerDaGreat57** [comment]
`project.json` just got a glowup.

While creating a sample `project.json` file for a fake hypothetical [crazy] project, I realized there were some spots in which I could make its structure more efficient and manageable.

There are two new types of objects: **Downloaders** and **Extractors**. Downloaders and Extractors are basically just template commands that are called whenever the script needs to download or extract an archive (while setting up dependencies). Due to the nature of this architecture (and a few other places in `project.json`) I also had to devise a way to let the user dynamically use values of other JSON data _inside_ others.

So now you can replace/append values inside JSON data with the notation `%{example.array[member].value}`. This notation can be slightly modified of course as all JSON data structures are not the same in the file, but it sticks to the `%{}` part. Basically, anything between the `{}` loosely matches the syntax used by `jq`, and will be replaced with whatever that value actually is. But this notation can only be used in places that I've used it in [`sampledefaults.json`](https://github.com/HackerDaGreat57/np/blob/main/.np_prototype/sampledefaults.json).

**Comment by HackerDaGreat57** [comment]
Now figuring out a basic algorithm to implement inside a custom ANSI formatting-insensitive text wrapping function.

[`_planning/goodlinewrapping.md`](https://github.com/HackerDaGreat57/np/blob/main/_planning/goodlinewrapping.md)

**Comment by HackerDaGreat57** [comment]
Ok so [that](https://github.com/HackerDaGreat57/np/issues/2) is getting kind of chaotic.

Meanwhile I am making some small changes to `project.json`:
1. Making it simpler by taking advantage of JSON's great syntax allowing nested objects. This makes it possible to group multiple related objects into one, making tag names shorter and simplifying the whole thing in general.
2. Adding underscores in JSON tag names. I honestly don't know why I didn't do this earlier.
